#jms_security_extra:
#    secure_all_services: false
#    expressions: true


security:
    enable_authenticator_manager: true

    providers:
        users:
            entity: { class: App\Entity\UserInfo, property: email }

    encoders:
        App\Entity\UserInfo:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_USER:        [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_REMEMBERED]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern: /.*
            provider: users
#            anonymous: ~
            lazy: true
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: /
#                remember_me: true
                success_handler: App\Handler\AuthenticationHandler
#            remember_me:
#                secret: '%kernel.secret%'
#                lifetime: 31536000 # in seconds
#                path: /
#                always_remember_me: false
#            remember_me:
#                key:      testing
#                lifetime: 31536000 # 365 days in seconds
#                path:     /
#                domain:   ~ # Defaults to the current domain from $_SERVER
            logout:
                path:   /logout
                target: /
                success_handler: App\Handler\AuthenticationHandler



    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/stayhome, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/new-gig, roles: ROLE_USER }
        - { path: ^/gig-center, roles: ROLE_USER }
        - { path: ^/gig/.*/studio, roles: ROLE_USER }
        - { path: ^/messages, roles: ROLE_USER }
        - { path: ^/studio, roles: ROLE_USER }
        - { path: ^/stats, roles: ROLE_USER }
        - { path: ^/connections, roles: ROLE_USER }
        - { path: ^/hire, roles: ROLE_USER }
        - { path: ^/paypal/pro/login, roles: ROLE_USER }
        - { path: ^/welcome/, roles: ROLE_USER }
        - { path: ^/stripe/identity, roles: ROLE_USER }
