version: "3.8"

services:
  php:
    build: ./docker/php/
    container_name: php
    ports:
      - 9999:80
    volumes:
      - ./:/var/www/html:rw
  db:
    image: mysql:5.7
    container_name: db
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3307:3307

  phpmyadmin:
    image: library/phpmyadmin:5.0-apache
    depends_on:
      - db
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80

  node:
    build: ./docker/node/
    container_name: node
    command: sh -c "yarn watch"
    depends_on:
      - php
    volumes:
      - ./app/:/var/www/html:rw
    ports:
      - 8081:8081
    working_dir: /var/www/html

volumes:
  data:
    driver: local
