version: '3.4'

services:
    php:
        build:
            context: ./docker/php
            target: vocalizr_php
        environment:
            - PHP_DATE_TIMEZONE=UTC
        volumes:
            - .:/srv/vocalizr
            - php-sessions:/srv/vocalizr/var/sessions
        container_name: "php_vocalizr"

    nginx:
        build:
            context: ./docker/nginx
            target: vocalizr_nginx
        depends_on:
            - php
        volumes:
            - .:/srv/vocalizr

volumes:
    php-sessions: