controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

_user_login:
    path:   /login
    controller: App\Controller\LoginController::index


_login_check:
    path:   /login_check

logout:
    path:   /logout
