imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: blocked_emails.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator: { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    templating:
        engines: ['twig']
        assets_version: v5.2.1
        assets_base_urls: '%assets_base_urls%'
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        handler_id: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    autoescape: false
    cache: "%kernel.cache_dir%/twig"
    globals:
      domain_base: %domain_base%
      facebook_app_id: %facebook_app_id%
      facebook_app_secret: %facebook_app_secret%
      facebook_app_scope: %facebook_app_scope%
      soundcloud_client_id: %soundcloud_client_id%
      audio_recorder_key: %audio_recorder_key%
      upload_audio_allowed: %upload_audio_allowed%
      upload_audio_allowed_extended: %upload_audio_allowed_extended%
      upload_assets_allowed: %upload_assets_allowed%
      default_date_format: %default_date_format%
      cdn_url: %cdn_url%
      stripe_api_key: %stripe_api_key%
      stripe_checkout_key: %stripe_checkout_key%
      paypal_url: %paypal_url%
      paypal_button_id: %paypal_button_id%
    form:
      resources:
        - 'VocalizrAppBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ VocalizrAppBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        default_entity_manager: default
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc
        connection: default
        dql:
            string_functions:
                ifelse: Vocalizr\AppBundle\DQL\IfElse
                date_format: Vocalizr\AppBundle\DQL\DateFormat
#                date_add: Vocalizr\AppBundle\DQL\DateAdd
            numeric_functions:
                rand: Vocalizr\AppBundle\DQL\Rand
                
doctrine_mongodb:
    connections:
        default:
            server: '%mongodb_dsn%'
            options: {}
    default_database: vocalizr
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Solarium Configuration
nelmio_solarium: 
    clients:
        default:
            host: localhost
            port: 8983
            path: /solr
            core: collection1
            timeout: 5
            
# Paging Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: VocalizrAppBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
hip_mandrill:
    api_key: wO8ZRfOhNBsrzrxRHD08BQ
    default:
        sender: notifications@vocalizr.com
        sender_name: vocalizr
