imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
