parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     
    database_name:     vocalizr
    database_user:     root
    database_password: 

    mailer_transport:  mail
    mailer_host:       ~
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            v0cal1zR*DSJu8DH347s
    
    domain_base:       local.vocalizr.com
    router.request_context.host: local.vocalizr.com
    router.request_context.scheme: http
    
    audio_recorder_key: 820f01581a603e68ad92c87c072d8a58

    facebook_app_id: 270724609723149
    facebook_app_secret: 4182c17474aabea8cd8b6d226478554f
    facebook_app_scope: email,user_birthday,user_location
    
    soundcloud_client_id: 2a742087e2ef470eaf157bca383386d1
    soundcloud_client_secret: 1a0a41aff336e48dbeb03448b6d486f2

    admin_email: john@smytheweb.com

    mail_from_email: john@smytheweb.com 
    mail_from_name: Vocalizr
    
    mail_subject_activation: Activate your account
    mail_subject_change_email: Email change request
    mail_subject_reset_pass: Reset your password request
    
    paypal_primary_email: john@vocalizr.com
    paypal_url: https://www.paypal.com/cgi-bin/webscr
    paypal_ipn_simulator_url: http://www.smytheweb.com/vocalizr/ipn.php?request=1
    paypal_test_mode: 1
    paypal_test_url: https://www.sandbox.paypal.com/cgi-bin/webscr
    paypal_currency: USD
    paypal_notify_url: http://www.smytheweb.com/vocalizr/ipn.php

    #paypal_client_id: 'Abe--Bccyp3dGuh6vvM9qHdxFz7e1LJwEt2wpECZetsjvoG-8RkRvKWYOgkDsGmz_QSxGVOqesI-S3GY'
    #paypal_client_Secret: 'EHUsOZWUYK8nUUmDnDJdBLWsRokYZXFPJGQcvfsJLMf7xQ6N-jXmcipygm299v-8lZdxhWNEXbBAvByD'
    
    paypal_env: 'sandbox'
    paypal_client_id: 'ASRkm-JnE56O-Ry6ZEGtrnaXR1Chs-oK0_raC6MiM34eFRpCdyyTUnatUqPELiPhNZixqnz-YifHfFLu'
    paypal_client_secret: 'ENh3qKuWTHiFazSIHYPR7jRK38vpwTp0Hk9o4XT43HF5hck2QNH8fpxMIWtcpOu7FCqP9CRVXgjqPtD8'

    paypal_legacy_api_username: 'timofey.n-test_api1.zimalab.com'
    paypal_legacy_api_password: 'W2FYCR9F3SUDANPZ'
    paypal_legacy_signature:    'AxpYDfrZEOWfawzZkLN7tKCy.BvJAOS8a4ZUsuHd6kb4UtHDYBikuud9'

    paypal_primary_email_subscriptions: subscriptions@vocalizr.com
    paypal_legacy_api_username_subscriptions: 'timofey.n-test_api1.zimalab.com'
    paypal_legacy_api_password_subscriptions: 'W2FYCR9F3SUDANPZ'
    paypal_legacy_signature_subscriptions:    'AxpYDfrZEOWfawzZkLN7tKCy.BvJAOS8a4ZUsuHd6kb4UtHDYBikuud9'

    paypal_stayhome_button_id: KQ39M4HJUWGV2
    paypal_button_id: RNBSZDUBJ65ME

    default_currency: USD
    
    upload_audio_allowed: mp3
    upload_audio_allowed_extended: mp3,aac,m4a
    upload_assets_allowed: mp3, wav
    
    
    default_date_format: M d, Y
    
    cdn_url: cdn.vocalizr.com
    
    connect_default_msg: "I'd like to add you to my professional network on Vocalizr."
    
    stripe_api_key: sk_test_kRDRu7DbJ2WW1wsggmBwf512 
    stripe_checkout_key: pk_test_85St7m9WpxTWbm5wBVyWi6Vf

    stripe_identity_api_key: sk_test_51H4avwCPLmtbtfKnM9p0OgCqwZzJzi0i2cueOz1NLR4GUdxkwdlXbM27YvQ6wcWTSXzHAbrEWwfvOP8aDKqsFaGN00TxdEcn34

    statistics_google_sheet_id: 1NWi-MhGrxztg6uKmxsMgkWvwzT9dHxXXJk-WUiaC1DQ
    statistics_google_list_name: Statistics

    pro_profile_enabled: false

    assets_base_urls: ~