parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     
    database_name:     vocalizr_test
    database_user:     vocalizr_test
    database_password: 7T*4W!W5j2uDFcl

    mailer_transport:  mail
    mailer_host:       ~
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            v0cal1zR*DSJu8DH347s
    
    domain_base:       test.vocalizr.com
    router.request_context.host: test.vocalizr.com
    router.request_context.scheme: http
    
    audio_recorder_key: 820f01581a603e68ad92c87c072d8a58

    facebook_app_id: 270724609723149
    facebook_app_secret: 4182c17474aabea8cd8b6d226478554f
    facebook_app_scope: email,user_birthday,user_location
    
    soundcloud_client_id: 2a742087e2ef470eaf157bca383386d1
    soundcloud_client_secret: 1a0a41aff336e48dbeb03448b6d486f2

    admin_email: john@vocalizr.com

    mail_from_email: noreply@vocalizr.com
    mail_from_name: Vocalizr
    
    mail_subject_activation: Activate your account
    mail_subject_change_email: Email change request
    mail_subject_reset_pass: Reset your password request
    
    paypal_primary_email: john@vocalizr.com
    paypal_url: https://www.paypal.com/cgi-bin/webscr
    paypal_ipn_simulator_url: http://www.smytheweb.com/vocalizr/ipn.php?request=1
    paypal_test_mode: 1
    paypal_test_url: https://www.sandbox.paypal.com/cgi-bin/webscr
    paypal_currency: USD
    paypal_notify_url: http://www.smytheweb.com/vocalizr/ipn.php
    
    default_currency: USD
    
    upload_audio_allowed: mp3
    upload_audio_allowed_extended: mp3,aac,m4a
    upload_assets_allowed: mp3, wav
    
    
    default_date_format: M d, Y
    
    cdn_url: cdn.vocalizr.com

    assets_base_urls: ~
