vocalizr_app:
    resource: "@VocalizrAppBundle/Controller/"
    type:     annotation
    prefix:   /
    
_user_login:
    pattern:   /login
    defaults:  { _controller: VocalizrAppBundle:Login:index }
    
_login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
