subscriptions:
    monthly: price_1H25V0FqlChUDt08cnY2JJns
    yearly:  price_1H4HjMFqlChUDt08QIJf11x7

products:
    restrict_to_preferences:
        id: prod_Hi3VWonm5Sa1z0
        prices:
            FREE: price_1H8dOuFqlChUDt08RsFA6uqU
            PRO:  price_1H8dV4FqlChUDt08fb7NhEG9

    to_favorites:
        id: prod_Hi3WoP2lNU1Qhq
        prices:
            FREE: price_1H8dPdFqlChUDt08IrxgHgdA
            PRO:  price_1H8dVoFqlChUDt08nbx2svic

    publish_type:
        id: prod_Hi3XGBC1bnseMb
        prices:
            FREE: price_1H8dQKFqlChUDt08RYvAu34C
            PRO:  price_1H8dQKFqlChUDt08kMdS4Ovy

    highlight:
        id: prod_Hi3YAV4N2vPVc8
        prices:
            FREE: price_1H8dRfFqlChUDt08VdYcYXth
            PRO:  price_1H8dRfFqlChUDt08au78scop

    featured:
        id: prod_Hi3a00UFX7RnOv
        prices:
            FREE: price_1H8dTGFqlChUDt08JGsw6h37
            PRO:  price_1H8dTGFqlChUDt08jPrZj6Xg

    messaging:
        id: prod_Hi3ZPMVZjqChdv
        prices:
            FREE: price_1H8dSQFqlChUDt08SW8biWD9
            PRO:  price_1H8dSRFqlChUDt08qfStARer

    lock_to_cert:
        id: prod_Hi3bBS3sCQ8Ujw
        prices:
            FREE: price_1H8dU5FqlChUDt08zC8ZeN7E
            PRO:  price_1H8dU5FqlChUDt08jpVnc93f

    extend_contest:
        id: prod_HsDhPIGM8QTjsy
        prices:
            5:  price_1HITGIFqlChUDt08KsKORhyO
            10: price_1HITGJFqlChUDt08ZchBDI4E
            15: price_1HITGIFqlChUDt08xeCwfAE9

    contest_budget:
        id: prod_Hi3tb9qxgoRnoI
        prices:
            150: price_1H8dmCFqlChUDt08iDJUN6go
            200: price_1H8dmBFqlChUDt08gu48r7o4
            300: price_1H8dmCFqlChUDt08YkGiuwy4
            400: price_1H8dmBFqlChUDt082bPfFMwj
            500: price_1H8dmCFqlChUDt08jhfZjs6Z
            700: price_1H8dmCFqlChUDt08rQjtdekj
            1000: price_1H8dmCFqlChUDt08fAYyfT8h

    extend_connections_limit:
        id: prod_HzkBzNJcbfMsn0
        price_values:
            10: 10
            25: 20
            60: 50
            140: 100
        prices:
            10: price_1HcoEYFqlChUDt08uyUGjIgc
            25: price_1HcoEYFqlChUDt08muYY3qe6
            60: price_1HcoEYFqlChUDt08eiCsNv17
            140: price_1HcoEYFqlChUDt08MzPIpYt2

    certified_user:
        id: prod_IBbmgi23JLjErH
        prices:
            yearly: price_1IIUdZFqlChUDt081YZu1Vs0

    paid_bid_highlights:
        id: prod_ICncvXIxzVkj0U
        price_values:
            1: 3.99
            2: 2.99
            3: 1.99
        prices:
            1: price_1IIUZ3FqlChUDt08M5mxy3Rn
            2: price_1IIUZ3FqlChUDt08aQkgrR6p
            3: price_1IIUZ3FqlChUDt08YH25O4ju
