subscriptions:
    monthly: price_1HClVhHsmITgfuvrfZlODHUO
    yearly:  price_1HTkWxHsmITgfuvrQQRnJ65k

products:
    restrict_to_preferences:
        id: prod_HlxW6rE6wuq22k
        prices:
            FREE: price_1HCPb1HsmITgfuvr9Eq0CsSZ
            PRO:  ~

    to_favorites:
        id: prod_HlxZN58I3GIFy4
        prices:
            FREE: price_1HCPeCHsmITgfuvrl2lDfsUL
            PRO:  ~

    publish_type:
        id: prod_Hlxb0HKDLCLm9J
        prices:
            FREE: price_1HCPfqHsmITgfuvr7BwgSbVE
            PRO:  price_1HCPfqHsmITgfuvrWeF6DfQQ

    highlight:
        id: prod_HuXbVr6r2kug7K
        prices:
            FREE: price_1HKiWaHsmITgfuvr20IIWvaN
            PRO:  price_1HKiWbHsmITgfuvrYjYfyRuM

    featured:
        id: prod_HuXbVr6r2kug7K
        prices:
            FREE: price_1HKiWaHsmITgfuvreA8R4c3m
            PRO:  price_1HKiWbHsmITgfuvrKs5Gb4O4

    messaging:
        id: prod_HuXbVr6r2kug7K
        prices:
            FREE: price_1HKiWbHsmITgfuvryXsF982Y
            PRO:  ~

    lock_to_cert:
        id: prod_HuXbVr6r2kug7K
        prices:
            FREE: price_1HKiWaHsmITgfuvrGnshVaKu
            PRO:  ~

    contest_budget:
        id: prod_HuX5moGA4tAD3g
        prices:
            150: price_1HKi1HHsmITgfuvrTbj2FfUk
            200: price_1HKi1IHsmITgfuvrC0PhloXl
            300: price_1HKi1IHsmITgfuvr1ZNS6dFg
            400: price_1HKi1IHsmITgfuvrzgqiOJAh
            500: price_1HKi1IHsmITgfuvrNx8VA5cX
            700: price_1HKi1IHsmITgfuvrrZV78iFz
            1000: price_1HKi1IHsmITgfuvrhuMhmDsX

    extend_contest:
        id: prod_HsFGnutkaRKpwW
        prices:
            5: price_1HIUlWHsmITgfuvr93UFTPID
            10: price_1HIUlWHsmITgfuvrIRN0Ems5
            15: price_1HIUlXHsmITgfuvrkOlK1bpg

    extend_connections_limit:
        id: prod_I7etXaxpC82V1Z
        price_values:
            10: 10
            25: 20
            60: 50
            140: 100
        prices:
            10: price_1HXPZfHsmITgfuvrnhTGJghc
            25: price_1HXPZgHsmITgfuvrwDzIszlx
            60: price_1HXPZeHsmITgfuvrBH6hDrpo
            140: price_1HXPZfHsmITgfuvrOkxRVW52

    certified_user:
        id: prod_ICV28S0btuzvyz
        prices:
            yearly: price_1IE6sjHsmITgfuvr1Cki42lS


    paid_bid_highlights:
        id: prod_IDJNCaAkLmqALZ
        price_values:
            1: 3.99
            2: 2.99
            3: 1.99
        prices:
            1: price_1IE75kHsmITgfuvrIF2QgSQt
            2: price_1IE75ZHsmITgfuvrQak9r252
            3: price_1IE75IHsmITgfuvrgWRg4bMQ
